server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agence_immobiliere
    username: agence
    password: agence123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

agence:
  app:
    jwtSecret: agenceImmobiliereSecretKey
    jwtExpirationMs: 86400000

logging:
  level:
    org.springframework.security: DEBUG
    com.agence: DEBUG 